#!/usr/bin/env bash
# Generate .env (random secrets) and config/providers.env (empty third-party keys), both chmod 600.
# Never overwrites existing files. Secrets are never printed.
set -Eeuo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "$0")/lib.sh"
env_file="${ROOT_DIR}/.env"
providers_file="${ROOT_DIR}/config/providers.env"
providers_example="${ROOT_DIR}/config/providers.env.example"
command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }
rand() { openssl rand -hex "$1"; }
umask 077

if [ -e "${env_file}" ]; then
  echo ".env already exists; leaving it unchanged (move it away first if you really want new secrets)." >&2
  env_status=1
else
  cat > "${env_file}" <<ENV
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
MYSQL_ROOT_PASSWORD=$(rand 24)
MYSQL_PASSWORD=$(rand 24)
REDIS_PASSWORD=$(rand 24)
COOKIE_SECRET=$(rand 32)
SORT_KEY_SECRET=$(rand 32)
MINIO_ROOT_USER=artcraft$(rand 4)
MINIO_ROOT_PASSWORD=$(rand 24)
API_PORT=12345
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001
WEBAPP_PORT=4201
# Browser-facing origin of the webapp (what you open through the SSH tunnel). Used for media links
# (MEDIA_CDN_BASE_URL) and baked into the webapp build. Keep host "localhost" (CORS/cookies, see docs).
# After changing: docker compose build webapp && docker compose up -d
WEBAPP_ORIGIN=http://localhost:4201
# Seed upstream system roles once when user_roles is empty (docker/migrate-entrypoint.sh).
AUTO_SEED_ROLES=true
# Backup retention is OFF by default (keep every backup). To auto-delete backups older
# than N days, uncomment and set a positive integer:
# BACKUP_RETENTION_DAYS=30
ENV
  chmod 600 "${env_file}"
  echo "wrote ${env_file} (mode 600)."
  env_status=0
fi

if [ -e "${providers_file}" ]; then
  echo "config/providers.env already exists; leaving it unchanged." >&2
else
  # Copy names from the tracked template, forcing every value to empty.
  sed -E 's/^([A-Z0-9_]+)=.*/\1=/' "${providers_example}" \
    | sed '1,2c\
# Generated by scripts/generate-secrets.sh. Gitignored. Fill in only the keys you need.' > "${providers_file}"
  chmod 600 "${providers_file}"
  echo "wrote ${providers_file} (mode 600, all values empty)."
fi
exit "${env_status}"
